name: clixily
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  bloc: ^8.1.0
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  intl: ^0.17.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  pretty_dio_logger: ^1.2.0-beta-1
  get_it: ^7.2.0
  flutter_localizations:
    sdk: flutter
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  environment_config: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true